spring:
  application:
    name: fiap--spring-cartao-credito
  #HACK https://github.com/springfox/springfox/issues/3462
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 5000

spring.data.mongodb:
  host: ${MONGODB_HOST:localhost}
  port: ${MONGODB_PORT:27017}
  database: ${MONGODB_DATABASE:db_aluno}
  username: ${MONGODB_USERNAME:admin}
  password: ${MONGODB_PASSWORD:admin}
  authentication-database: ${MONGODB_AUTH_DATABASE:admin}